# HDFS
HDFS_CLIENT_URI = ''
HDFS_DEFAULT_USER = ''

# HTTP CODE
HTTPError = ''

# KAFKA PRODUCER
ACKS = ''
# 可选值：sasl_ssl, PLAINTEXT
SECURITY_PROTOCOL = 'PLAINTEXT'
# 可选值：PLAIN
SASL_MECHANISM = ''
PRODUCER_SASL_PLAIN_USERNAME = ''
PRODUCER_SASL_PLAIN_PASSWORD = ''

# KAFKA CONSUMER
BOOTSTRAP_SERVERS=''
TOPIC = ''
GROUP_ID = 'pro_test_lsl'
# 三种可选：earliest, latest, none
AUTO_OFFSET_RESET = 'latest'
CONSUMER_SASL_PLAIN_USERNAME = ''
CONSUMER_SASL_PLAIN_PASSWORD = ''